apiVersion: v2
name: brigade-noisy-neighbor
description: |
  A Helm chart for Brigade Noisy Neighbor
type: application
version: 0.1.0
appVersion: v0.1.0
sources:
- https://github.com/brigadecore/brigade-noisy-neighbor
maintainers:
- name: The Brigade Maintainers
  email: cncf-brigade-maintainers@lists.cncf.io
